### ISSUE TITLE
Failed deploy to aws instance does not fail test

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#63]
The DeployFuture sees the failed wget command but continues to process the deploy request.

16:22:05.148 DEBUG [PslclBlockingExecutor-11] c.p.d.c.r.resource.staf.StafSupport -
StafSupport.issueProcessShellRequest:
        ProcessCommandData:
                host: 52.91.110.126
                fdn: false
                basePath: /opt/dtf/sandbox/bin
                fileName: testrun.sh
                fileOnly: false
                sandbox: /opt/dtf/sandbox
                command: sudo wget -O 87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422 http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422
                wait: true
                timeout: 0
                useWorkingDir: true
                context: null
                stafCmd = process start shell command "sudo wget -O 87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422 http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422" wait returnstdout returnstderr workdir /opt/dtf/sandbox/bin
                StafRunnableProgram:
                        running = false
                        ProcessResult:
                                rc = 0 - Ok
                                result = @SDT/*:1065:@SDT/{:587::13:map-class-map@SDT/{:559::35:STAF/Service/Process/CompletionInfo@SDT/{:261::4:keys@SDT/[3:189:@SDT/{:56::12:display-name@SDT/$S:11:Return Code:3:key@SDT/$S:2:rc@SDT/{:48::12:display-name@SDT/$S:3:Key:3:key@SDT/$S:3:key@SDT/{:55::12:display-name@SDT/$S:5:Files:3:key@SDT/$S:8:fileList:4:name@SDT/$S:35:STAF/Service/Process/CompletionInfo:35:STAF/Service/Process/ReturnFileInfo@SDT/{:198::4:keys@SDT/[2:126:@SDT/{:56::12:display-name@SDT/$S:11:Return Code:3:key@SDT/$S:2:rc@SDT/{:50::12:display-name@SDT/$S:4:Data:3:key@SDT/$S:4:data:4:name@SDT/$S:35:STAF/Service/Process/ReturnFileInfo@SDT/%:456::35:STAF/Service/Process/CompletionInfo@SDT/$S:1:4@SDT/$0:0:@SDT/[2:384:@SDT/%:60::35:STAF/Service/Process/ReturnFileInfo@SDT/$S:1:0@SDT/$S:0:@SDT/%:303::35:STAF/Service/Process/ReturnFileInfo@SDT/$S:1:0@SDT/$S:241:--2016-02-11 16:22:04--  http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.

```
                            key = null
                            serviceCcode = 4
                            stopCcode = null
                            fileList:
                                    ReturnFileStreams: stdout
                                            rc: 0
                                            data:
                                    ReturnFileStreams: stderr
                                            rc: 0
                                            data: --2016-02-11 16:22:04--  http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422
```

Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.

```
                    ProcessCommandData:
                            host: 52.91.110.126
                            fdn: false
                            basePath: /opt/dtf/sandbox/bin
                            fileName: testrun.sh
                            fileOnly: false
                            sandbox: /opt/dtf/sandbox
                            command: sudo wget -O 87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422 http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422
                            wait: true
                            timeout: 0
                            useWorkingDir: true
                            context: null
```

**16:22:05.148 WARN  [PslclBlockingExecutor-11] c.p.d.c.r.r.s.futures.DeployFuture - Staf requested process failed: --2016-02-11 16:22:04--  http://localhost/content/87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.**

16:22:06.242 DEBUG [PslclBlockingExecutor-11] c.p.d.c.r.resource.staf.StafSupport -
StafSupport.issueProcessShellRequest:
        ProcessCommandData:
                host: 52.91.110.126
                fdn: false
                basePath: /opt/dtf/sandbox/bin
                fileName: testrun.sh
                fileOnly: false
                sandbox: /opt/dtf/sandbox
                command: sudo mv 87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422 testrun.sh
                wait: true
                timeout: 0
                useWorkingDir: true
                context: null
                stafCmd = process start shell command "sudo mv 87D9EF34046CFEB17B37A1675BB943C2525A11F53FE0189E94C6072F0BF86422 testrun.sh" wait returnstdout returnstderr workdir /opt/dtf/sandbox/bin
...
